### ISSUE TITLE
DragonBurg update/remodel

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII-Map#12]
Reworking blocks used to make things nicer/redecorate.  Add quest(s) for the new quest location.  Add NPC's for shops as well as any needed for additional quests

**Comment by teagan75** [comment]
almost done with redoing the main streets and lampposts of DragonBurg. Was going to basically clone and copy the shopkeepers from Draconis to place in DragonBurg but change gender/skin/names :) Have also seen a few unique shops to add in NPC traders :) Then I was going to work on the insides of some of the main buildings.

**Comment by GreatOrator** [comment]
This will work well, and we can use the unique shops to fill gaps people have requested?

**Comment by teagan75** [comment]
Copied the following merchants. Changed names and skins. 
1. Fish merchant
2. Florist
3. vegetable merchant
4. fruit vendor
5. Innkeeper (with new room keys)
6. Barkeep

**Comment by teagan75** [comment]
Merchants and redecorating are done. Starting to add the two quest lines I have come up with.

**Comment by teagan75** [comment]
DragonBurg is complete.
