### ISSUE TITLE
Map Shop Owner -DB

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#18]
Possible future addition of treasure maps leading to small-large rewards depending on difficulty.

**Comment by GreatOrator** [comment]
As awesome of an idea as this is, I think the work involved for doing this would put way too much on our plate at this point.

Up to you, but I think what he have outlined currently will be more than enough at this point?

**Comment by GreatOrator** [comment]
Think this idea will be shelved in lieu of everything else we have added
