### ISSUE TITLE
Aragorn's role in the map - ideas

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#19]
I have been looking through a timeline that attempts to puts all of Tolkien's stories in order. http://lotrproject.com/timeline/

I also saw that Aragorn (Thorongil) took  "a small Gondor squadron of ships, [and] led an assault on the long-standing rebel province of Umbar in 2980, burning many of the Corsairs' ships and personally slaying their lord during the battle on the Havens. After the victory at Umbar, "Thorongil" left the field and, to the dismay of his men, went east."

"Later in 2980, he visited Lórien, and there once again met Arwen. He gave her the heirloom of his House, the Ring of Barahir, and, on the hill of Cerin Amroth, Arwen pledged her hand to him in marriage, renouncing her elvish lineage and accepting the Gift of Men: death."

"Before the events of The Lord of the Rings properly take place, Aragorn also traveled through the Dwarven mines of Moria, to Harad, where (in his own words) "the stars are strange." Tolkien does not specify when these travels occurred nor does he indicate what happens when Aragorn visits."

http://lotr.wikia.com/wiki/Aragorn_II_Elessar

**Comment by GreatOrator** [comment]
we may be able to work something in, I was contemplating trying to get another eastern faction build in if possible, angmar

**Comment by teagan75** [comment]
I have a map that would work for Umbar too if you are interested.

**Comment by GreatOrator** [comment]
I have added him in for part of a quest line already in the upcoming release.  I think we will leave it at that for now unless you had other ideas?

**Comment by GreatOrator** [comment]
Aragorn/Strider now has a proper role in the new quest line, unless some minor ones are thought up, going to close this out.
