### ISSUE TITLE
Ladders in draconis

### ISSUE THREAD

**Issue by ProsperCraft** [GreatOrator/TolkienCraftII-Map#2]
Please punch out the bottom rung of the ladders so creepers don't enter the town and cause panic.

**Comment by GreatOrator** [comment]
I am not sure how they would escape unless someone leaves a door open. Is this really needed?  Newest release of DE will make it so the creepers despawn like they are supposed to and as far as I know, all the chunkloaders (aside from the default spawn chunks) should be gone as well.
