### ISSUE TITLE
Beorn's role in the map - ideas

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#20]
"While Gandalf knew him, Beorn did not know Gandalf; but he knew his cousin, Radagast."

So maybe a quest that includes both of these characters eventually?

"He did not eat any meat, as he could talk with his animals, who helped him. His grove was occupied by huge bees. Beorn's diet was mainly honey and cream."

Maybe the beekeeper in Draconis could eventually lead players to Beorn for more advanced bee quests?

**Comment by GreatOrator** [comment]
I seriously think this is a good plan, Have a skin for beorn already.  Will add him in at least and consider this idea for the next content update.

**Comment by GreatOrator** [comment]
Did we still want to consider a quest line for this? or simply add his NPC so finish out his house?

**Comment by GreatOrator** [comment]
What is the current status on this?  Did we end up with a quest set here after all?

**Comment by teagan75** [comment]
yes we have quests in Beorn's area...will be adding them to the HQM list

**Comment by GreatOrator** [comment]
Alright, will close this out as complete then since the rest will go in the HQM thread
