### ISSUE TITLE
Grey Havens

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII-Map#28]
Grey Havens will be a mini FT point from rivendell or lothlorien and terrain modified to be grass rather than ice and stone

**Comment by GreatOrator** [comment]
Grey Havens has been added for 2.8 with FT, but the build is incomplete for regular use so has been moved to 2.9.x update.

**Comment by GreatOrator** [comment]
Build has been updated and fixed, only need to populate with NPC's/spawners for mobs, to make it a living location.

**Comment by teagan75** [comment]
Dale, Esgaroth, Forochel and Norgrod could use populating as well.

Edit: nvm about Dale...the new npcs have populated :smile: 
Edit#2: well not every part of Dale is populated

**Comment by GreatOrator** [comment]
Aye, forochel was on my list, dale should have NPC's already, though they probably spread out after placement, will look into nogrod and esgaroth, problem with lake-town is the water...npc's love the water

**Comment by teagan75** [comment]
Erebor is pretty empty if you don't have that on the list.

**Comment by GreatOrator** [comment]
Alright, all areas have now been updated with npc's (assuming they don't all get killed :P ) calling this done!
