### ISSUE TITLE
Game crash when creating a new world

### ISSUE THREAD

**Issue by axelsbh** [GreatOrator/TolkienCraftII-Map#3]
i just downloaded the lastest template folder and putted it in the monecraft folder but it keeps crashing when i create a new world... i tried redownloading all but still crashing...

**Comment by axelsbh** [comment]
ok... for everyone that have the same problem its just that the first map loading is REALLY long to load took me 5 minutes so try to wait 5 minutes.

**Comment by GreatOrator** [comment]
yup, that is normal, it depends on the speed of your hard drive to copy the template over.
