### ISSUE TITLE
Blue Mountains/Nogrod

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#31]
Build by teagan75, Ghorgen and Jerle17

**Comment by GreatOrator** [comment]
If we can get a dwarvish stable installed, I can add a fast travel point here if it will be done in time for release.

**Comment by teagan75** [comment]
Sorry I will tell my brother...completely forgot about this :)

**Comment by GreatOrator** [comment]
Going to call this build complete
