### ISSUE TITLE
2.8 Pre-release bugs

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#33]
HQM Questbook
The "In of the Prancing Pony" should read "Inn of the Prancing Pony"

Also in that quest, the location point for Ethan is set for upstairs and should be near him.

**Comment by teagan75** [comment]
HQM Questbook
Maybe you could write this blurb in the quest "Choose Wisely"

The fate of Middle Earth hangs in the balance and it is up to you to choose a side  -  forever leaving your imprint in the world of Arda.

**Comment by teagan75** [comment]
HQM Questbook
(My fault hehe)
Quest - "To Osgiliath"
There should be three tasks - unfortunately you will need to re-do the tasks because the one that needs to be added is first. It will confuse players if we don't change this...I am so sorry.
1. Location Task
   Title: Commander of the South Army
   Location: 85625 67 63440
2. Location Task
   Title: Finding a Scout
   Location: 79667 64 65655
3. Location Task
   Title: Supply Locations
   Crate 1: 79547 69 65599
   Crate 2: 79731 67 65773
   Crate 3: 79561 65 65939

**Comment by teagan75** [comment]
HQM Questbook
Quest - Festival of the Dancing Fireflies
Location is wrong and up in the air :(
Sky Ritual
Location: 55082 69 22236

**Comment by teagan75** [comment]
HQM Questbook
Quest - The Stage is Set
1. Reducing Threat
   Location task: Mount Doom 92691 115 60651
2. Power of Mount Doom
   Detection task: 0/1 palantir shard
3. Informing the Order
   Khamul Location: 67731 60 21148

**Comment by teagan75** [comment]
NPC quest: Job Board - Bree/Archet
1. NPC (Sybilla Lytton) asks you to kill pigs but then the quest log says warg fur.
2. NPC (Philippa Sadler) asks you for Orc bones but the quest log says raw porkchop
3. There is a missing pages quest listed in the Custom NPCs for missing pages but HQM doesn't list it

**Comment by GreatOrator** [comment]
All HQM corrections made, NPC stuff is all that remains

**Comment by teagan75** [comment]
HQM Job Board - Eriador
"Trying to Leave"
Dwarf Camp has no coords

**Comment by GreatOrator** [comment]
Alright, fixed all of the job board quests to reflect the proper trigger for availability, also corrected the coords that were missing in HQM.

**Comment by GreatOrator** [comment]
Done and Done!
