### ISSUE TITLE
HQM suggestion

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#36]
Val mentioned that if you are grouped with HQM and trying to do job boards, if one person in the party completes the location, the other players cannot see it anymore. She suggested that we put the coords into the text of each of the quests as well to avoid that.

**Comment by GreatOrator** [comment]
I am going to look into this, also going to suggest a feature for journeymap, a console command to add waypoints :)

**Comment by GreatOrator** [comment]
So the waypoint command never played out.  Thinking possibly creating a map with a point saved for the atlas we give players.  only issue there is the fact that minecraft likes to reset those stupid maps

**Comment by GreatOrator** [comment]
I have put additional thought into this.  Not sure exactly how we will pull this off as there are several waypoints I want to add to HQM to help players locate the quest points being added.  Though I have attempted to be as clear as possible without giving specific coordinates for each one of them.

**Comment by GreatOrator** [comment]
Yeah, no work-around for this unfortunately, so will have to make it work the way it is right now.
