### ISSUE TITLE
Bartender - Hobbiton

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#37]
The quest for Family Heirloom won't complete location possibly due to the location block not being uploaded with the map update. Will investigate.

Also, fix his dialog to open up after Thin Their Numbers and to include the role

**Comment by teagan75** [comment]
Hamfast Gamgee can be repeatable and make all of them give rep

**Comment by GreatOrator** [comment]
the ring quest family heirloom?  if so, location block should be there (it is buried near the front door of bag end's entrance, sill check along with other items.

**Comment by teagan75** [comment]
No I wrote the wrong quest name for this one lol. I know which quest it is but forget the name. It is the bartenders side quest.

**Comment by teagan75** [comment]
ok this quest is fixed
