### ISSUE TITLE
Troll room

### ISSUE THREAD

**Issue by Delerium** [GreatOrator/TolkienCraftII-Map#4]
Please remove the anti-build in the troll boss room.  Since gravestone saves your items on the ground when you die, if you die in one of these "no build" zones, your entire inventory gets deleted.

**Comment by GreatOrator** [comment]
Because of the amount of stuff there that can be taken, the anti builders have to stay.  This is one of the reasons there are mentions about making sure you are geared up and prepared for the fight before going in.  An alternative is to turn on keep inventory to avoid that issue.

**Comment by Delerium** [comment]
You should mention the potential for losing your items then, because most boss fights in any game will say something like "make sure you are geared up before going in".  It's a pretty general statement to make in a game.  Also, I don't think keep inventory works with gravestone installed.  To be honest, no modpack should ever have the potential for absolute item loss like this with no warning.  I lost quite a bit of work and had no idea gravestone would not function in that room.  It leaves a sour taste in my mouth.

**Comment by GreatOrator** [comment]
It does, several people have videos where they have turned it on, and there are mentions in the text about making sure your ready

**Comment by Delerium** [comment]
"Make sure you are ready" does not mean "Gravestone does not work in this fight."  Period.  There's no way I could have known that would happen and most people trust gravestone to work.
