### ISSUE TITLE
not spawning right location plus some question

### ISSUE THREAD

**Issue by killmetohell** [GreatOrator/TolkienCraftII-Map#48]
when i updated my map it spawn me in middle-earth for no reason. i don't know why the map update was 2.8.x rc6. i have some few question after i updated it said i had missing mod i solve some of it but it said i was missing 3 thermal expansion items i don't know know if i have with version of thermal expansion or i do but can you tell what thermal expansion version ur using for it or if its some other mod.
fyi note when i spawn in the middle-earth some reason have i have a bottomless pouch with items with and draconic helm.

**Comment by GreatOrator** [comment]
First, there was a derp with FTB, the RC6 was intended for version 2.8.6 of the pack.  They are working to fix it, sorry, was out of my control. Second, most likely the reason you are getting placed in the wrong spawn area was I probably forgot to remove my data from the level.dat so will fix that as well once ftb fixes the version on the launcher.

**Comment by killmetohell** [comment]
good to know weird although i can't find tolkiencraft on ftb for odd reason well it just wierd thing for me might figure might missing it or not

**Comment by killmetohell** [comment]
oh ya do have to manually update the map for main one if i have one already exist.

**Comment by GreatOrator** [comment]
Well, it is bak under a code for ftb at tolkienadv2 but the update SHOULD be up now and I fixed the map
