### ISSUE TITLE
can't Find npc?

### ISSUE THREAD

**Issue by killmetohell** [GreatOrator/TolkienCraftII-Map#50]
i don't know if i should but this here but i can can't find a certain npc which is ylander which apparently the farmer. Do know anyway where i can find npc or tp npc or other wise because for reason the npc isn't at farm nor showing up in npc wand.

**Comment by GreatOrator** [comment]
If he has for some reason disappeared you can either reset the map or use the clone tool (the axe) as he SHOULD be in the list of available clones

**Comment by killmetohell** [comment]
k thanks i'll check

**Comment by killmetohell** [comment]
ok i clone him looks everything when fine with him now i'm trying to figure why the reinforcements quest for i think customnpc doesn't let me finish.

**Comment by GreatOrator** [comment]
what is the issue? do you get the items to place? and if so, are you placing them in the correct area?

**Comment by killmetohell** [comment]
well i placed the items but i'm not sure if i placed them in right place because it said i had discover them but when i placed them is location i think that they need to be placed and i went back the npc don't remember name right now and got same dialogue.

by the way do place them on Chiseled Stone Brick because i thought that sense its usually normal do put a spot or something to know where to exactly to put them.

**Comment by GreatOrator** [comment]
The chiseled blocks are the correct location, you just need to make sure you are also physically in the locations you need to be as well

**Comment by killmetohell** [comment]
it said i did said that i found location. so not sure how much physically i need to be in location.

side note for unknown reason when i got back location it keep saying southern location found know any reason it keep saying every-time i go near the location.

**Comment by teagan75** [comment]
The other issue with that quest completing may be that it says to find the Mage tower again before talking to the Mage. Try exiting and returning to Mage tower. Or move to the doorway at the back of the top room.

**Comment by killmetohell** [comment]
i'll check on that

**Comment by killmetohell** [comment]
i checked on it it seem it did not ask me to return to the mage tower.
from looks of it i still asking for placement of the golems.

**Comment by killmetohell** [comment]
i'll go try to see if new map makes a difference

**Comment by killmetohell** [comment]
ya it made a difference the new map i used seem let solve it i guess some reason the quest got bugged and got stuck know anyway to reset it or something.

**Comment by GreatOrator** [comment]
not without actually being in the map, no

**Comment by killmetohell** [comment]
oh well

**Comment by Snaxs** [comment]
Have the same problem with Ylander and being new to this, I need a little help.  Clone tool?  Where can I find that?

**Comment by GreatOrator** [comment]
Creative mode, customnpc tab
