### ISSUE TITLE
Recipe Mode Crash and missing Ylander

### ISSUE THREAD

**Issue by Snaxs** [GreatOrator/TolkienCraftII-Map#51]
First, loving the Tolkiencraft II!!
My issues -
1. If I try to select anything from recipe mode or any other mode, the whole game crashes.  I have 16GB of RAM and have tried changing the amount allocated, no luck.
2. Ylander, I can't find him.  I read that their is a clone tool but I have no idea where it is or how to use it.
3. BDcraft, I'd like to use this skin but only maybe half of the items load.  I'm guessing I need to asks the folks at BDcraft for help on this issue?
4. Other than here, can you link me a place or two for help?  A forum?   I'm still new to the Minecraft world, please be kind.
5.  Just thanks again for creating Tolkiencraft!!

**Comment by GreatOrator** [comment]
Has been exlained in previous reports, solution at the ftb forum post, I would suggest checking there.

**Comment by Snaxs** [comment]
OMW!!!

Thanks again!
