### ISSUE TITLE
tyltran will not die 

### ISSUE THREAD

**Issue by ahouseman1** [GreatOrator/TolkienCraftII-Map#52]
I was playing through the quests in tolkincraft II and I got to the part where you must kill tyltran. I took the diamond sword from the chest and started hitting him with it it said i was dealing crit hits but he was loosing no health please help me

**Comment by GreatOrator** [comment]
Make sure command blocks are turned on if you are on a server, make sure you are on the quest to kill him, try talking to elmn on the docks to fix it (if you are on the quest line)

One of those three or multiple are the reason.

**Comment by teagan75** [comment]
You also may not be hitting the trolls hitbox. That is an issue with that boss. Try hitting him in different spots hehe

**Comment by ahouseman1** [comment]
just had to talk to the guy on the dock and ask him to fix the boss thanks!
