### ISSUE TITLE
HQM Changes

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#60]
In the chapter, Quest Journal, for the eastern line, change:

To Osgiliath ---> Hire a Scout
      subdivided
          1. To Minas Ithil
          2. To Osgiliath

**Comment by GreatOrator** [comment]
Also need to add a Forodwaith job board

**Comment by GreatOrator** [comment]
Did we have a bunch of little quests to add to forochel and surrounding area?  if so, going to add a job board, otherwise I won't

**Comment by teagan75** [comment]
Yes I will be adding quests to Forochel soon

**Comment by GreatOrator** [comment]
Alright, then I will add it to my list of things to put in

**Comment by teagan75** [comment]
I have 4 quests for Forochel (and quests within those quests) so yeah this section can be closed once the OP change is made.

**Comment by GreatOrator** [comment]
Yeah, I specifically left the HQM ones open since that is what I will be working on over the next couple of days

**Comment by GreatOrator** [comment]
Need to remind myself to make sure the Mirkwood and Forochel Job boards get entered into the book as well

**Comment by GreatOrator** [comment]
I was just looking over the To Osgiliath Quest...how exactly did you want it changed?  Right now it has three stages, Southern Army, finding a Scout, and supply locations.  I think if you mean to add another quest button could potentially break the book for existing worlds #becausehqm

**Comment by teagan75** [comment]
Then just leave it alone 😄

**Comment by GreatOrator** [comment]
Alright, then this issue can finally be closed!  So very close!
