### ISSUE TITLE
HQM Quests Added

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII-Map#65]
Copy below for each new quest:

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Rhovanion

Quest Title: The Marsh-Bell

Main Quest Text: Glóin is looking for adventurers willing to take on a dangerous task.

Quests - Type: Location
- Title: Dwarf Ambassador
- Coords: 83678 67 -12373

Text for each quest: The dwarf can be found in his office in Esgaroth.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Rhovanion

Quest Title: Rivers Run with Gold

Main Quest Text: A merchant named Baldor is looking to hire some armed guard for travel into Mirkwood.

Quests - Type: Location
- Title: Caravan
- Coords: 83396 70 -12475

Text for each quest: Sounds like easy coin!

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Kinstrife and Dark Tidings

Main Quest Text: You heard that men have settled in the land of Beorn and their rivers are teeming with fish. Maybe you can earn some coin trading with the Beornings.

Quests - Type: Location
    - Title: Attacked Boat
    - Coords: 62842 63 -6488

Text for quest: After the Battle of the Five Armies, Beorn extended an invitation for men to come and settle on his land. Nobody knows why he did so, and nobody seems able to divine his plans for the future. Beorn seems content today as a leader of folk as he seemed once to enjoy his previous isolation.

```
 - Title: Beorn's Hall
 - Coords: 63056 81 -6358
```

Text for quest: You should take the bodies of the two dead Beornings to Beorn is his hall. Looks like there is a path along the river.

Reward For completion: same coin as the others and two GraveStone villager corpses: beekeepers (i know but you will see lol)

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Folk-moot of Rhosgobel

Main Quest Text: Looks like the Woodsmen of Mirkwood are holding a meeting. In times of need, the Elders from all Houses meet at a folk-moot to make important decisions that concern them all. Maybe you could listen in and see what the news is around the area.

Quests - Type: Location
     - Title: Meet Ingomer
     - Coords: 68286 68 4040

Text for each quest: The Woodsmen of Wilderland are not united under a crown, but are divided into several Houses, as they call a group of clans or families who dwell together in the same great hall under a common token of kinship.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Staff of the Road Warden

Main Quest Text: Bofri has come to the folk-moot to seek adventurers to help him acquire a lost staff for the warden of the Old Forest Road.

Quests - Location
    - Title: Bofri
    - Coords: 68300 68 4045

Text for each quest: A dwarf who bears the staff and is acknowledged as Warden of the Road increases his standing among the dwarves of Erebor.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: The Questing Beast

Main Quest Text: This year, the Elvenking has extended an invitation to mortals to join in the hunt of the White Hart. Elven hunters spotted one in Northern Mirkwood. The hunter that kills the beast will be feasted in Thranduil's Hall.

Quests - 
1. Location
     - Title: Elvenking
     - Coords: 77978 104 -12951
2. Location
     - Title: White Deer
     - Coords: 78030 81 -12571

Text for each quest: For many years, King Thranduil has hunted the fabled white elk of Mirkwood, a race of enchanted beasts known to roam all of the forest. They are rarely seen, and some consider their appearance to foreshadow portentous events.

Reward For completion:  Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: The Beast of the Forest

Main Quest Text: You hear tales of the triumphant return of a hero as you travel through the Woodland Realm. You decide to join in the celebratory feast held in his honor.

Quests - Type: Location
     - Title: Elven Feast
     - Coords: 78201 94 -12617

Text for each quest: Angered by the Werewolf's attack on the Bower, King Thranduil dispatched his hunters. One of them, a brave knight Orophal, tracks the beast to its lair in the Mountains of Mirkwood. He is wounded in the fight but slays the beast.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Paying the Troll

Main Quest Text: You meet two travelling Dwarves coming from the Grey Mountain Narrows.

Quests - Type: Location
- Title: Frar, the Beardless
- Coords: 77873 62 -12430
  Text for quest: Frar the Beardless' mission is to enlist the help of the Dwarves of Erebor to help him reclaim the Greydelve, a Dwarven fortress lost in the north. He makes frequent trips to the Halls of the Elvenking as well as Erebor.
- Title: Troll Camp
- Coords: 78097 76 -12404
  Text for Quest: maybe some lore about Half-trolls (you know more than me)

Text for each quest: Frar the Beardless' mission is to enlist the help of the Dwarves of Erebor to help him reclaim the Greydelve, a Dwarven fortress lost in the north. He makes frequent trips to the Halls of the Elvenking as well as Erebor.

Reward For completion: Same as normal job board quests

**Comment by GreatOrator** [comment]
This is just a simple note for the job board at Rhosgobel:

Location 68306 69 4036

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Wheels Within Wheels

Main Quest Text: While traveling along the Old Forest Road in Eastern Mirkwood, you come upon the aftermath of a battle between Orcs and men from Dale.

Quests - Type: Location

Title: Battle Scene
Coords: 84830 72 -4848
Text for quest: You find two Dalish men still alive and decide to talk to them.

Title: Outlaws' Lair
Coords: 84729 77 -4716
Text for quest: The Outlaws decided to flee at the first sign of trouble confirming that this was an ambush.

Reward For completion: Same as normal job board quests

**done to here

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Of Leaved and Stewed Hobbit

Main Quest Text: You have heard of a new Hobbit run inn in the village of Stonyford within the lands of Beorn. People have raved about Agatha's cooking! Time to sit back, enjoy good food and drink, and listen to the latest gossip!

Quests - Type: Location

Title: Easterly Inn
Coords: 63292 73 -6509
Text for quest: Dody Brandybuck met Bilbo Baggins while in Bree. The two fell to sharing stories, and for once Dody was the one who was flabbergasted and entranced by the other's stories of distant lands. This is what inspired him to convince his wife and brother to open an inn in the Wilderland.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Beorn's Quest

Main Quest Text: You heard around Stonyford that Beorn wanted to speak with you. He is about to make a speech to his followers in his hall.

Quests - Type: Location

Title: Beorn's Hall
Coords: 63047 81 -6375

Text for each quest: Some lore about Beorn (you know more than me)

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mirkwood

Quest Title: Those Who Tarry No Longer

Main Quest Text: While traveling along the Elf-path in the Woodland Realm, you come upon a group of Elves travelling the path as well.

Quests - Type: Location

Title: Borders of the Forest
Coords: 78508 74 -12690
Text for quest: One of the Elves in the party is Galion, former cupbearer of King Thranduil, consigned to patrol duty for drunkenness since the famous escape of a group of Dwarves from the royal halls.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Blue Mountains or Adventure Lads

Quest Title: Adventure of a Lifetime

Main Quest Text: Talk to Náin in Belegost about a possible adventure.

Quests - Type: Location

Title: Frustrated Miner
Coords: -23451 72 -11722

Text for quest: In the latter part of the Third Age, the Dwarves settled the Blue Mountains again when Thráin II and his son Thorin and the Dwarven survivors of the Sack of Erebor moved from Dunland and delved a prosperous settlement there.

Title: The Pits of Utumno
Coords: 42165 69 -42939

Text for Quest: "But in the north Melkor built his strength, and he slept not, but watched and laboured; and the evil things that he had perverted walked abroad, and the dark and slumbering woods were haunted by monsters and shapes of dread. And in Utumno he gathered his demons about him, those spirits who first adhered to him in the days of his splendour, and became most like him in his corruption" - The Silmarillion

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Mordor or Adventure Lads

Quest Title: Adventure of a Lifetime

Main Quest Text: Talk to Nagug outside Barad-dur about a possible adventure.

Quests - Type: Location

Title: Frustrated Miner
Coords: 97680 81 59808

Text for each quest: Barad-dûr was the Dark Lord Sauron's primary stronghold in Mordor, serving as his base of operations in Middle-earth during the Second and Third Ages.

Title: The Pits of Utumno
Coords: 42165 69 -42939

Text for Quest: "But in the north Melkor built his strength, and he slept not, but watched and laboured; and the evil things that he had perverted walked abroad, and the dark and slumbering woods were haunted by monsters and shapes of dread. And in Utumno he gathered his demons about him, those spirits who first adhered to him in the days of his splendour, and became most like him in his corruption" - The Silmarillion

Reward For completion: Same as normal job board quests
**done to here

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Forochel

Quest Title: Nightmares of Angmar

Main Quest Text: Head to the town of the Lossoth at the Bay of Forochel and speak with Elder Gávgu. He will be found in the large castle on the north side of town.

Quests - Type: Location

Title: Fear in Our Hearts
Coords: 2181 100 -32094

Text for quest: The Lossoth, also called the Snowmen of Forochel, were Men, survivors of the Forodwaith, the ancient people from the northern lands of Middle-earth.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Forochel

Quest Title: Harder Than Stone

Main Quest Text: "Crazy" Yuri needs your help locating his friends.

Quests - Type: Location

Title: Crazy, am I?!
Coords: 2124 66 -31897

Text for quest: Morgoth created the first Trolls before the First Age. They were strong and vicious but stupid creatures. Their major weakness was that they turned to stone in sunlight. Nobody knows how Morgoth managed to breed them, though Treebeard says that Trolls were "made ... in mockery of Ents", as Orcs were of Elves.

Title: Fishing Dock
Coords: 2238 80 -32503

Text for quest: The Lossoth survive in the harsh wastes of Forochel by ice fishing and hunting other sea animals, such as seal and whale.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Forochel

Quest Title: Frozen War

Main Quest Text: Ándaras, in the hall of Elders, in Forochel could use some help against their enemy.

Quests - Type: Location

Title: Hall of Elders
Coords: 2181 99 -32094

Text for quest: There are many dangers in Forochel but perhaps the greatest danger of all is the howling wind that blows over the mountain sides and across the frozen waters. 

Title: Susi-väki Village
Coords: 2351 70 -31928

Text for quest: The chief enemy of the Lossoth are the savage and brutal Susi-väki ('wolf-people'). They live in small villages or camps in the Forodwaith.

Reward For completion: Same as normal job board quests

**Comment by teagan75** [comment]
Main Section: Job Board Middle Earth - Forochel

Quest Title: Hunters in the Waste

Main Quest Text: Láilá, in the hall of Elders, in Forochel could use some help against their enemy.

Quests - Type: Location

Title: Hall of Elders
Coords: 2181 99 -32094

Text for quest: The Lossoth are wary if not outright suspicious of foreigners from the South, or etalävieras as they call us, but once they have warmed up to you most are kind and hospitable.

Title: Susi-väki Village
Coords: 2351 70 -31928

Text for quest:  It is fairly certain that Tolkien, when creating the men of Forochel, based them off the Finnish people especially the Sami.

Reward For completion: Same as normal job board quests

**Comment by GreatOrator** [comment]
Quests added and updated on dev server, files in discord to test today

**Comment by GreatOrator** [comment]
Re-opening because I forgot I needed to add 3 quests, one for the scavenger hunt, one for gollum and one to point players to the new npc in isengard

Current Fixes needed:
Location name for Mirkwood Area changed to Rhosgobel
Add reward for Forochel - Hunters in the Waste
Fix Spelling of Beorlings to Beornings in Kinstrife and Dark Tidings

**Comment by teagan75** [comment]
oh...I couldn't think for the life of me what 3 quests you still needed :)

**Comment by GreatOrator** [comment]
Done!
