### ISSUE TITLE
Special Soulstone  NPCs

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#8]
We could possibly add special soulstoned NPCs that are unique from any of the others we can find and interact with already in the game. Players can put them in their bases. Maybe they have a special quest to complete or a special inventory to sell.

They would become available for purchase or as a reward after a quest line or completing all the job board quests in a region.

**Comment by GreatOrator** [comment]
I am thinking a banker one would be nice, one of the issues I have had is requiring players to always go to town to use the bank, would be nice to have some sort of ATM at their base, maybe use one of the elemental mobs from blood magic to give it a cool look

**Comment by GreatOrator** [comment]
Have figured out how this would work, first item, ATM!

Looks like we could easily create "pets" using this

**Comment by GreatOrator** [comment]
So far I have created a few pets, want to have at least 6 to choose from when done. A few I have done so far: Bear, Chicken and bunny

**Comment by GreatOrator** [comment]
We will continue to use this issue like the skins one, just a place to record ideas for these special types of NPC's

**Comment by teagan75** [comment]
These skins can be used for various dog pets: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1242471-requests-are-taken-rockys-mo-wolves-custom-wolf

Used version 3 (unfortunately github wouldn't let me upload the folder)
i just put the folder into the CustomSkins folder

**Comment by GreatOrator** [comment]
Since the pet idea did not work out as we had hoped (meh, go figure :D ) going to close this out.
