### ISSUE TITLE
New NPC's

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII-Map#9]
In an effort to make things even more organized for us, I want to start using this issue to track any new npc's we add (new npc's that we need skins for)

Use this format:

Skin Link:
Folder:

So if we pull a skin from say planetminecraft, we would put the link there and then name the folder (including case) we add the skin to (such as Hobbit, etc)  This way if we add a skin we can all download an put it in the right location to see it on the dev server.

**Comment by GreatOrator** [comment]
Saruman

Skin: http://www.planetminecraft.com/skin/saruman-2108224/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
Thinking this could be used as an NPC in middle earth for a side quest/one of the longer quests

[name not chosen]

Skin: http://www.planetminecraft.com/skin/the-dark-ranger-3026439/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
[Name not Chosen]

Skin: ![daenalanthalas](https://cloud.githubusercontent.com/assets/8086758/10062525/303c25a8-6218-11e5-8803-efdc23ce2d1e.png)
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
[Name not Chosen]

Skin: ![stablemaster](https://cloud.githubusercontent.com/assets/8086758/10062843/ebba7a48-621b-11e5-9ebe-1a4c368c6b42.png)
Folder: MiddleEarth

Skin: ![stableapprentice](https://cloud.githubusercontent.com/assets/8086758/10062849/fd2f7ba2-621b-11e5-894f-fce72827aece.png)
Folder: MiddleEarth

**Comment by teagan75** [comment]
Crazy Yuri

Skin: http://www.planetminecraft.com/skin/fisherman-1223102/
File Name: CrazyYuri.png
Folder: Guy

**Comment by GreatOrator** [comment]
Sn0w

Skin: ![snowshepherds-skin](https://cloud.githubusercontent.com/assets/8086758/10193883/8e86457c-673a-11e5-9855-e92d95942477.png)
Folder: MiddleEarth
File Name: SnowShepherds-skin.png

---

Eastern Alliance Stable Master/Apprentice

Skin: ![darkelfstablemasterskintcii-ss](https://cloud.githubusercontent.com/assets/8086758/10193902/ab59ef5a-673a-11e5-954a-9a92f3b3f422.png)
Folder: MiddleEarth
File Name: darkElfStableMasterSkinTCII-SS.png

**Comment by teagan75** [comment]
DBGuard

skin: 
![dbguard](https://cloud.githubusercontent.com/assets/12485764/10238335/e913a620-6883-11e5-9f6d-15f808f0ae84.png)

Folder: TownsPeople
File name: DBGuard.png

**Comment by GreatOrator** [comment]
Tom Bombadill

Skin: http://www.planetminecraft.com/skin/tom-bombadil-an-unexpected-return/
Folder: MiddleEarth
File Name: Whatever name PM gives when downloading.

**Comment by teagan75** [comment]
Pawnbroker

Skin: 
![pawnbroker](https://cloud.githubusercontent.com/assets/12485764/10269939/19960d70-6aa9-11e5-881d-c414362d093d.png)

Folder: Towns People
File name: Pawnbroker

**Comment by teagan75** [comment]
Shyla Trevil

skin: 
![shyla trevil](https://cloud.githubusercontent.com/assets/12485764/10272119/6bed810c-6ae0-11e5-9657-626340f1312b.png)

Folder: Girl
File name: Shyla Trevil.png

**Comment by teagan75** [comment]
Medieval Noble

skin:
![medievalnoble](https://cloud.githubusercontent.com/assets/12485764/10292701/50399b6c-6b76-11e5-94f3-9c0f136a2479.png)

File name: MedievalNoble.png
Folder: Guy

**Comment by teagan75** [comment]
(Barliman?) Butterbur

skin: http://www.planetminecraft.com/skin/barliman-butterbur-tvp/

Folder: MiddleEarth

**Comment by GreatOrator** [comment]
King Thranduil

skin: http://www.planetminecraft.com/skin/the-hobbit-thranduil-the-elvenking/
Folder:MiddleEarth

**Comment by GreatOrator** [comment]
Goldberry

Skin: ![goldberry](https://cloud.githubusercontent.com/assets/8086758/10382424/caebdbf4-6dd8-11e5-952f-1a67468da832.png)

Folder: MiddleEarth
File Name: goldberry.png

**Comment by GreatOrator** [comment]
Theoden

Skin: http://www.planetminecraft.com/skin/theoden-lotr/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
Beorn

Skin: http://www.planetminecraft.com/skin/beorn-the-hobbit-desolation-of-smaug/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
Radagast

Skin: http://www.planetminecraft.com/skin/radagast-the-brown---from-the-hobbit/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
Witch King of Angmar

Skin: http://minecraft.novaskin.me/skin/10746240/download
Folder: MiddleEarth

---

Ringwraith

Skin: http://minecraft.novaskin.me/skin/4660435833847808/download
Folder: Middle Earth

**Comment by teagan75** [comment]
Lady Galadriel
![galadriel](https://cloud.githubusercontent.com/assets/12485764/10462612/479cd20a-71a5-11e5-94fe-a0b37fb76105.png)

Folder: MiddleEarth

File name: Galadriel

Lord Celeborn
![celeborn](https://cloud.githubusercontent.com/assets/12485764/10462618/4ff32882-71a5-11e5-8d26-d54b5662c335.png)

Folder: MiddleEarth

File name: Celeborn

**Comment by teagan75** [comment]
Lady Eornis ( eastern main quest npc)

![ladyeornis](https://cloud.githubusercontent.com/assets/12485764/10462827/5ae9247a-71a6-11e5-99a3-2d189dc100c0.png)

Folder: MiddleEarth

File name: LadyEornis

**Comment by teagan75** [comment]
Tzerlag: Orc Scout

![tzerlag](https://cloud.githubusercontent.com/assets/12485764/10471719/3e20f772-71de-11e5-81e4-06a91cb60a18.png)

Folder: MiddleEarth

File name: Tzerlag

**Comment by teagan75** [comment]
Cirdan, the Shipwright

Skin: http://www.planetminecraft.com/skin/crdan-the-shipwright/

Folder: MiddleEarth

**Comment by teagan75** [comment]
Denethor

Skin: 
![denethor](https://cloud.githubusercontent.com/assets/12485764/10522713/42c1c4fa-733c-11e5-8304-5586af44fb61.png)

Folder: MiddleEarth

File name: Denethor

**Comment by GreatOrator** [comment]
Grima Wormtongue

Skin: http://www.planetminecraft.com/skin/grima-wormtongue--tvp/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
Ailbeart - Water Fast Travel

Skin: http://www.planetminecraft.com/skin/wine-merchant/
Folder: MiddleEarth

**Comment by GreatOrator** [comment]
I want to keep using this but only for NPC's that we intend to reuse (fast travel guys, etc) since we seem to have worked out a good system for the general skins we are using.

**Comment by GreatOrator** [comment]
Closing out since I think the bulk of new NPC's have been completed
